# render.yaml
services:
  - type: web
    name: crypto-arbitrage-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: DATABASE_URL
        value: sqlite:///arbitrage.db
      - key: TG_BOT_TOKEN
        value: your-token-here
      - key: TG_CHAT_ID
        value: your-chat-id-here
