services:
  - name: crypto-arbitrage-backend
    type: web_service
    env: docker
    dockerfilePath: Dockerfile.backend
    plan: starter
    envVars:
      - key: API_AUTH_KEY
      - key: BINANCE_API_KEY
      - key: BINANCE_API_SECRET
      - key: TG_BOT_TOKEN
      - key: TG_CHAT_ID

  - name: crypto-arbitrage-frontend
    type: web_service
    env: docker
    dockerfilePath: frontend-ui/Dockerfile
    plan: starter
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        value: https://crypto-arbitrage-backend.onrender.com/api
